name: Test
on:
  workflow_dispatch:
jobs:
  RunOneScript:
    runs-on: ubuntu-latest  
    runs:
      using: 'node20'
      main: 'main.js'
      steps:

      - uses: actions/checkout@v3
      - uses: otymko/setup-onescript@v1.4
        with:
          version: 1.9.0 
          
      - name: Запускаем OneScript
        run:  opm update 
            opm install -all
            oscript ./executionScript.bsl
